### ISSUE TITLE
mongodb Alternative

### ISSUE THREAD

**Issue by NicoCG** [advorange/Advobot#5]
@advorange,

Could you kindly implement mongodb as a alternative database option 👍

**Comment by advorange** [comment]
I'm not sure how efficient my implementation is, but MongoDB can be used with the bot now.

To use it you'll need to supply some command line arguments:
```
-DatabaseType MongoDB -DatabaseConnectionString "mongodb://localhost:27017"
```

(Replace the connection string with your connection string)

**Comment by NicoCG** [comment]
@advorange Thank you for adding this.
